### ISSUE TITLE
GUI wrong behavior when temperature is automatically computed

### ISSUE THREAD

**Issue by rikigigi** [lorisercole/thermocepstrum#57]
![image](https://user-images.githubusercontent.com/33728857/151988685-98892854-c14c-4c6e-a145-c1afd03c5a2f.png)
then after loading a new file, the messages are wrong
![image](https://user-images.githubusercontent.com/33728857/151988854-6d0ef2af-bfca-43f4-b13f-053cbd01576b.png)
wrong reading of the temperature when opening a table file from scratch: the temperature field is editable, but if it is edited, it is silently ignored
![image](https://user-images.githubusercontent.com/33728857/151989175-214dbecb-568f-4a9e-8796-9b134fc80eff.png)

**Comment by rikigigi** [comment]
fixed by 122468f63eb0a3f1462d627f69f2f70e157d0340

**Comment by lorisercole** [comment]
Hey @rikigigi, thanks for fixing this.
I still see a minor problem in the case of a 'table' input file. Try with the `NaCl.dat` example data.
Temperature is one of the columns. 
The Temperature box in the "set variables" window is disabled, but the value reported is zero.
![image](https://user-images.githubusercontent.com/30901257/156395031-d640bc43-f5d5-412d-91e7-a1a912e7f095.png)
However, it is computed fine: if you go to the next window and come back it will appear :)

**Comment by rikigigi** [comment]
Yes, the problem is that the table file is read only in the next step, as it may take a long time. This would require a bigger refactoring. The numpy file is read immediatly, and it is much faster, so in this case the temperature is displayed here

**Comment by lorisercole** [comment]
Ok understood. Let's leave it like that then!
Thanks
